import { bigint, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Shared column builders. With `casing: "snake_case"` (see `drizzle.config.ts`)
 * the camelCase property key drives the column name, so these are unnamed.
 */

/** UUID primary key, generated by Postgres. */
export const pk = () => uuid().primaryKey().defaultRandom();

/**
 * Money column. All money in Black Stars is **whole KES shillings** stored as
 * `bigint` (mode "number") — no sub-unit, matching the prototype dataset, the
 * `money()`/`moneyK()` UI helpers, Kenyan practice and M-Pesa. See
 * `docs/decisions/0002-money-storage.md`.
 */
export const money = () => bigint({ mode: "number" });

/**
 * Audit columns spread into every table. `createdBy` is a nullable user id,
 * wired to real Stack Auth users in Phase 4 (who recorded this row).
 */
export const timestamps = {
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
  createdBy: uuid(),
};

/** Audit columns for append-only ledgers (no `updatedAt`). */
export const ledgerStamps = {
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  createdBy: uuid(),
};
